-- MySQL Script generated by MySQL Workbench
-- Mon Oct  1 12:59:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_java` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_java` ;

-- -----------------------------------------------------
-- Table `db_java`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_java`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(30) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_java`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_java`.`courses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_java`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_java`.`students` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(30) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `fullname` VARCHAR(80) GENERATED ALWAYS AS (CONCAT(firstname,' ',lastname)) VIRTUAL,
  `cellphone` CHAR(9) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_java`.`inscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_java`.`inscriptions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `courses_id` INT UNSIGNED NOT NULL,
  `students_id` INT UNSIGNED NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `registration_date` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inscriptions_courses_idx` (`courses_id` ASC) VISIBLE,
  INDEX `fk_inscriptions_students1_idx` (`students_id` ASC) VISIBLE,
  CONSTRAINT `fk_inscriptions_courses`
    FOREIGN KEY (`courses_id`)
    REFERENCES `db_java`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscriptions_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `db_java`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
